NAME		= opt-nfswatch
VERSION		= 4.99.11
RELEASE		= 0
TARBALL_POSTFIX	= tar.gz
RPM.EXTRAS      = "AutoReq: no"

SRC_SUBDIR      = nfswatch

SOURCE_NAME     = nfswatch
SOURCE_VERSION  = $(VERSION)
SOURCE_SUFFIX   = tar.gz
SOURCE_PKG      = $(SOURCE_NAME)-$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR      = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

TAR_GZ_PKGS     = $(SOURCE_PKG)
